name: scan_master_app
description: "A premium Material 3 Document Scanner and PDF Toolkit app"
publish_to: 'none'

version: 1.5.53+176

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: any
  camera: any
  image_picker: any
  pdf: any
  printing: any
  file_picker: any
  path_provider: any
  permission_handler: any
  share_plus: any
  google_mobile_ads: any
  image: any
  google_mlkit_text_recognition: any
  google_mlkit_document_scanner: any
  signature: any
  qr_flutter: any
  mobile_scanner: any
  open_filex: any
  gal: any
  package_info_plus: any
  shared_preferences: any
  url_launcher: any
  archive: any
  pro_image_editor: any
  flutter_local_notifications: any
  pdf_manipulator: any
  pdfrx: 2.6.1
  receive_sharing_intent: 1.8.0
  reorderable_grid_view: any
  quick_actions: any
  syncfusion_flutter_pdf: any
  local_auth: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_performance: any
  firebase_analytics: any
  firebase_in_app_messaging: any
  firebase_messaging: any
  firebase_remote_config: any
  workmanager: any
  local_auth_android: any
  local_auth_darwin: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
