// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOK_WG2tPUX6FHjqCORgYVDJtQXxzDT8',
    appId: '1:302398516430:web:aee6e5a5caa37ab083749f',
    messagingSenderId: '302398516430',
    projectId: 'scanmaster-55e57',
    authDomain: 'scanmaster-55e57.firebaseapp.com',
    storageBucket: 'scanmaster-55e57.firebasestorage.app',
    measurementId: 'G-D963CXZD5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvk1keYhja6AMac-Z71jEN1b8CaZOrLXY',
    appId: '1:302398516430:android:d84d03fea8b82b9483749f',
    messagingSenderId: '302398516430',
    projectId: 'scanmaster-55e57',
    storageBucket: 'scanmaster-55e57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdUiycaSqoHREsDFzJffDOaIjmsY3fPMU',
    appId: '1:302398516430:ios:11cc50031ac89bc083749f',
    messagingSenderId: '302398516430',
    projectId: 'scanmaster-55e57',
    storageBucket: 'scanmaster-55e57.firebasestorage.app',
    iosBundleId: 'com.scanmaster.scanMasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdUiycaSqoHREsDFzJffDOaIjmsY3fPMU',
    appId: '1:302398516430:ios:11cc50031ac89bc083749f',
    messagingSenderId: '302398516430',
    projectId: 'scanmaster-55e57',
    storageBucket: 'scanmaster-55e57.firebasestorage.app',
    iosBundleId: 'com.scanmaster.scanMasterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEOK_WG2tPUX6FHjqCORgYVDJtQXxzDT8',
    appId: '1:302398516430:web:3821bde8a32cb32d83749f',
    messagingSenderId: '302398516430',
    projectId: 'scanmaster-55e57',
    authDomain: 'scanmaster-55e57.firebaseapp.com',
    storageBucket: 'scanmaster-55e57.firebasestorage.app',
    measurementId: 'G-STMPQ08W2H',
  );
}
